### ISSUE TITLE
Fetch API - modular architecture

### ISSUE THREAD

**Issue by dietza** [JeffKersting/refactor-tractor-whats-cookin#10]
As a developer,

When I am building out the structure (or refactoring architecture) for an app,

I want to separate the methods responsible for Fetch API calls,

So that the project has a more modular file structure and is consequently more DRY&SRP.

- [x] create `Fetch-API.js` in src directory (we don't need to test these methods here)
- [x] will need to import / export 

file structure will be similar to:

```
// Fetch-API.js

let Fetch-API = {
  getData1(){...},
  postData2(){...},
  ...
};

export default  Fetch-API;
```

**Comment by srslie** [comment]
Created the post dynamic function, need to import it into scripts.

**Comment by srslie** [comment]
This is completed!
