### ISSUE TITLE
Fetch-API POST requests (add and remove ingrds. to/from pantry)

### ISSUE THREAD

**Issue by dietza** [JeffKersting/refactor-tractor-whats-cookin#11]
As a User,

When I have decided to cook a recipe (call method adding recipe to user.toCook array),

I want to be able to add and subtract relevant ingredients / amounts from my pantry,

So that the data reflected in my pantry is up-to-date reflecting used/depleted and restocked ingredient amounts.

 - If the currently displayed user has an ID of 50, and you want to add 3 units of an ingredient with an ID of 123, you would want to send a JSON object through with your POST request that looks like:

```
{
  "userID": 50,
  "ingredientID": 123,
  "ingredientModification": 3
}
```

- If you wanted to remove 3 units of that ingredient, you’d want to send a JSON that looks like this:

```
{
  "userID": 50,
  "ingredientID": 123,
  "ingredientModification": -3
}
```

**Comment by srslie** [comment]
Created an apis file for this with a dynamic function that gets users or ingredients or recipes.
