### ISSUE TITLE
create README.md

### ISSUE THREAD

**Issue by dietza** [JeffKersting/refactor-tractor-whats-cookin#28]
As a developer,

When I building a project,

I want to write a clean README.md,

So that the intent, development lifecycle and (current) state of the project are well-documented. This should make it easy for other developers to understand the project, including its goals and limitations / problems, and to contribute to the project if applicable.

(not all of these sections may feel as relevant on this project)
- [ ] Project OverView / Purpose & intention
- [ ] Deployed Page?
- [ ] Use (instructions & gifs/visuals)
- [ ] Architecture / file structure
- [ ] Technologies & tools
- [ ] Instructions for download / installation, Dependencies
- [ ] Wins / Challenges
- [ ] Plans for continued development / future iterations
- [ ] Contributors (w/ GH links)

**Comment by srslie** [comment]
This is started, I would like some folks to take a look to:
- add ideas for future iterations
- anyone to thank in contributions
- update once we have a deployable github page link
- update with gifs
