### ISSUE TITLE
DOM updates - modular architecture

### ISSUE THREAD

**Issue by dietza** [JeffKersting/refactor-tractor-whats-cookin#8]
As a developer,

When I am building out the structure (or refactoring architecture) for an app,

I want to separate the methods responsible for DOM-updates,

So that the project has a more modular file structure and is consequently more DRY&SRP.

- [x] create `domUpdates.js` in src directory (we don't need to test these methods here)
- [x] will need to import / export 

file structure will be similar to:

```
// domUpdates.js

let domUpdates = {
  updateDomMethod1(){...},
  updateDomMethod2(){...},
  ...
};

export default  domUpdates;
```

examples to import from separate file:
showMyRecipesBanner() on line 241
showWelcomeBanner() on line 246

**Comment by srslie** [comment]
This file is created and currently takes care of card creation, togglingling, clearing and updating html, pantry display, listing tags, showing recipe comparison, and is importing properly.
